// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/accounts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/accounts/index.get').default>>>>
    }
    '/api/plaid/exchange-token': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/plaid/exchange-token.post').default>>>>
    }
    '/api/plaid/link-token': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/plaid/link-token.post').default>>>>
    }
    '/api/plaid/recurring': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/plaid/recurring.get').default>>>>
    }
    '/api/plaid/sync': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/plaid/sync.post').default>>>>
    }
    '/api/transactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transactions/index.get').default>>>>
    }
    '/api/transactions/summary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transactions/summary.get').default>>>>
    }
    '/api/waitlist': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/waitlist.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}