// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/25/2026, 4:18:36 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/shelby/.openclaw/workspace/spendfixer-web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/shelby/.openclaw/workspace/spendfixer-web/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/shelby/.openclaw/workspace/spendfixer-web/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/shelby/.openclaw/workspace/spendfixer-web/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/shelby/.openclaw/workspace/spendfixer-web/app/plugins/**/*.{js,ts,mjs}","/home/shelby/.openclaw/workspace/spendfixer-web/app/composables/**/*.{js,ts,mjs}","/home/shelby/.openclaw/workspace/spendfixer-web/app/utils/**/*.{js,ts,mjs}","/home/shelby/.openclaw/workspace/spendfixer-web/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/shelby/.openclaw/workspace/spendfixer-web/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/shelby/.openclaw/workspace/spendfixer-web/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/shelby/.openclaw/workspace/spendfixer-web/app/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;